directories:
  output: release
  buildResources: build
appId: com.xiaokuaiji.app
productName: 小会计
files:
  - filter:
      - dist/**/*
      - electron-main.cjs
      - server.ts
      - package.json
electronVersion: 31.0.0
win:
  target:
    - target: portable
      arch:
        - x64
asar: true
asarUnpack:
  - node_modules/better-sqlite3
